integrations:
  virustotal:
    enabled: false  # Set to true to activate
    api_key: "YOUR_VIRUSTOTAL_API_KEY"
    fields: ["ip", "domain", "file_hash"]
  abuseipdb:
    enabled: false
    api_key: "YOUR_ABUSEIPDB_API_KEY"
    fields: ["ip"]
  hybrid_analysis:
    enabled: false
    api_key: "YOUR_HYBRID_ANALYSIS_API_KEY"
    fields: ["file_hash", "ip", "url"]