tenants:
  tenant1:
    name: "Empresa A"
    token: "abcde12345"
    data_sources:
      - name: "linux_auth"
        path: "/var/log/auth.log"
        enabled: false
        module: "linux"
        event_types: [1001, 1002, 1007, 1004, 1006]
        filters: {}

      - name: "linux_syslog"
        path: "/var/log/syslog"
        enabled: false
        module: "linux"
        event_types: [1004]
        filters: {}

      - name: "wazuh_alerts"
        path: "/var/ossec/logs/alerts/alerts.json"
        enabled: false
        module: "wazuh_file"
        event_types: [100001, 100002, 100003]  # IDs que devem ser permitidos
        filters:
          agent_ids: ["001", "002"]

      - name: "crowdstrike"
        path: "/var/log/crowdstrike/events.log"
        enabled: false
        module: "crowdstrike"
        event_types: [111171, 111172]
        filters:
          sensor_ids: ["CS-01", "CS-02"]

      - name: "o365_alerts"
        path: "/var/ossec/logs/alerts/alerts.json"
        enabled: false
        module: "wazuh_o365"
        event_types: [91556]  # IDs que devem ser permitidos
        filters:
          organization_ids: ["abcdefg"]

  tenant2:
    name: "Empresa B"
    token: "zyxw98765"
    data_sources:
      - name: "linux"
        path: "/var/log/auth.log"
        enabled: false
        module: "linux"
        event_types: [1003, 1008, 1009]
        filters: {}

      - name: "wazuh_alerts"
        path: "/var/ossec/logs/alerts/alerts.json"
        enabled: false
        module: "wazuh_file"
        event_types: [100001, 100002, 100003]  # IDs que devem ser permitidos
        filters:
          agent_ids: ["001", "002"]

      - name: "crowdstrike"
        path: "/opt/logs/cs.log"
        enabled: false
        module: "crowdstrike"
        event_types: []
        filters: {}
