data_sources:
  - name: linux_auth
    module: linux
    path: /var/log/auth.log
    enabled: true
    event_types: [1001, 1002, 1003, 1004, 1005, 1006, 1007, 1009]

  - name: linux_syslog
    module: linux
    path: /var/log/syslog
    enabled: true
    event_types: [1008, 1009]
