tenants:
  tenant1:
    name: "Empresa A"
    token: "abcde12345"
    data_sources:
      - name: "linux_auth"
        path: "/var/log/auth.log"
        enabled: true
        module: "linux"
        event_types: [1001, 1002, 1007, 1004, 1006]
        filters: {}

      - name: "linux_syslog"
        path: "/var/log/syslog"
        enabled: true
        module: "linux"
        event_types: [1004]
        filters: {}

      - name: "wazuh_alerts"
        path: "/var/ossec/logs/alerts/alerts.json"
        enabled: false
        module: "wazuh"
        event_types: [1111002, 111111003]
        filters:
          agent_ids: [10, 11, 12]

      - name: "crowdstrike"
        path: "/var/log/crowdstrike/events.log"
        enabled: false
        module: "crowdstrike"
        event_types: [111171, 111172]
        filters:
          sensor_ids: ["CS-01", "CS-02"]

  tenant2:
    name: "Empresa B"
    token: "zyxw98765"
    data_sources:
      - name: "linux"
        path: "/var/log/auth.log"
        enabled: true
        module: "linux"
        event_types: [1003, 1008, 1009]
        filters: {}

      - name: "wazuh_alerts"
        path: "/var/ossec/logs/alerts/alerts.json"
        enabled: false
        module: "wazuh"
        event_types: [10021111]
        filters:
          agent_ids: [45, 46, 47]

      - name: "crowdstrike"
        path: "/opt/logs/cs.log"
        enabled: false
        module: "crowdstrike"
        event_types: []
        filters: {}
